from scapy.all import *

# packet = Ether()/IP(dst='E4:18:6B:4B:94:00')/TCP(dport=53,flags='S')

# dot11 = Dot11(type=0, subtype=8, addr1='E4:18:6B:4B:94:00', addr2='33:33:33:33:33:33', addr3='33:33:33:33:33:33')

# packet = Ether()/dot11/TCP(dport=53,flags='S')

data = "UFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJUFRRJU"

# sendp(Ether(src="aa:bb:cc:dd:ee:ff")/data/IP(src="192.168.1.122", dst="192.168.1.9")/TCP(sport=135,dport=135), count=2000)


# # sendp(Ether(src="aa:bb:cc:dd:ee:ff")/Ether(src="aa:bb:cc:dd:ee:ff", dst="E4:18:6B:4B:94:00")/TCP(sport=135,dport=135), count=2000)

# dot11 = Dot11(type=2, subtype=0, addr1='E4:18:6B:4B:94:00', addr2='11:11:11:11:11:11', addr3='33:33:33:33:33:33')

dot11=  Ether(src="aa:bb:cc:dd:ee:ff", dst="E4:18:6B:4B:94:00")

# beacon = Dot11Beacon(cap='ESS+privacy') ## indica a capacidade do ponto de acesso


# essid = Dot11Elt(ID='SSID',info='testSSID', len=len('testSSID'))


frame = RadioTap()/dot11/data

frame.show()


sendp(frame, iface='wlp3s0', inter=0.1, loop=0, count=300) # inter = intervalo entre o envio dos pacotes
